version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::533267269037:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-kxivboMWF9gp"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::533267269037:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-07M0OX6O03LY"
cloudformation_execution_role = "arn:aws:iam::533267269037:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-nA7PyXjrkx3J"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-ly6e2azfuggn"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::533267269037:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-zJgqrqvxOIsS"
cloudformation_execution_role = "arn:aws:iam::533267269037:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-JAE5NdcoS5T8"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-ek23lbeh8slz"
image_repository = ""
region = "us-east-1"
